### ISSUE TITLE
O que vamos usar no projeto?

### ISSUE THREAD

**Issue by HenriqueMundim** [Laranja-Mecanica/orange-portifolio-api#1]

**Comment by HenriqueMundim** [comment]
Typescript e Express, pois não é um projeto muito robusto

**Comment by eoSalinas** [comment]
Acho interessante também utilizarmos alguns conceitos SOLID para trazer mais qualidade para o código, junto de testes unitários para garantir a robustez e que o sistema não desmorone com uma nova feature.

**Comment by eoSalinas** [comment]
Como havíamos conversado @HenriqueMundim vamos manter o padrão de commits com o conventional commits e style code com lint também, porém ainda vamos definir qual será as regras do lint.

**Comment by HenriqueMundim** [comment]
No quesito de banco de dados, chegamos em acordo em utilizar postgreSQL em conjunto com o prismaORM
