### ISSUE TITLE
Fix no problema de tipagem do customRequest (Express)

### ISSUE THREAD

**Issue by eoSalinas** [Laranja-Mecanica/orange-portifolio-api#31]
- [x] Fix tipagem
- [x] Reestruturar `req.userId` que recupera as informações do usuário logado, para um payload ou algo do tipo que seja mais reutilizável

**Comment by HenriqueMundim** [comment]
Encontrei uma forma de implementar isso sem criar um tipo novo de Request, apenas utilizando o recurso de declaration merging.

**Comment by eoSalinas** [comment]
Boaa! Você é um gênio meu amigo! Estou curioso para ver essa resolução
